[build]
  command = "echo 'No build step needed for htmz'"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/htmz-proxy"
  to = "/.netlify/functions/htmz-proxy"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/dist/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"